### PR TITLE
Experiment/documentation

### PR DESCRIPTION
**Pull request by chunfantasy**
There are huge amount of lines changed but most of them are in docs/
Mainly changes are only in two files: `packge.json` and `pre-commit.js`

Updates for the documents:
* Has scrolled side bar
* Has filter to search contents
* Does not affect many line changes after each commit although for this time the number is huge.
* Looks a bit nicer.
* Can be reusable in other projects as well.

Please verify locally whether it works or not on your pc, particularly on linux and mac.

### CODE REVIEW

**Comment by mrodem** [comment]
There is room for improvement on the commit messages here. Recommended reading: https://chris.beams.io/posts/git-commit/

**Comment by chunfantasy** [comment]
Worth to read! 👍

**Comment by bihanssen** [comment]
We've actually been using that article as guideline without noting it down. I just added it on [confluence](http://projecttools.nordicsemi.no/confluence/display/WYLND/Git) for reference.

**Comment by mrodem** [comment]
Tested this on Linux. In my case it generated a large diff of seemingly unrelated sections in index.html. Also tried the markdown output, but that ended up being very large and difficult to navigate.

If the pre-commit approach does not work out, then I have an alternative proposal. We are using GitHub Pages which can be set up to always show whatever is on the `gh-pages` branch. On our build server we could create a task that simply generates the docs, commits them to the `gh-pages` branch, and pushes it to origin. There is actually an npm package for this: https://www.npmjs.com/package/gh-pages. With this approach we avoid messing up the pull requests and commit history with unreadable diffs from the doc generator.

**Comment by mrodem** [comment]
Nice research/experimentation here, but closing this PR as it has now been made obsolete by #80. Staying with jsdoc for now. If we want to replace it with documentation.js, then that should be done in a separate PR.

**Pull request closed without merging**
