### PR TITLE
introduce typings for usage with typescript

### PR DESCRIPTION
**Pull request by ksachdeva**
Please see an example of usage here - https://github.com/ksachdeva/pc-ble-driver-js-examples/tree/master/nrf5x_apps_typescript

This is still work in progress. Will do following in coming days -

- [ ] add documentation
- [ ] add definitions for more types/classes

### CODE REVIEW

**Comment by rosek86** [comment]
Hi @ksachdeva,

I wrote an initial typescript definition for nRF5x js driver which we successfully use in our project. Please check it here https://github.com/rosek86/nrf5x-typescript/blob/master/nrf5x.d.ts, possibly it will be useful for you too.

It is still 'work in progress' too, but for simple communication (without authentication etc) it works fine.

Regards,
Krzysztof

**Comment by ksachdeva** [comment]
Thanks Krzysztof, your typings look good. I specially liked the overloading of EventEmitter 'on' methods. Let's collaborate on getting them part of this module so we do not have to install them separately. Once this pull request is accepted then either you or I can incorporate changes from your typings into this one.

Regards & thanks
Kapil

**Comment by bihanssen** [comment]
@ksachdeva Thanks for the contribution. Let us know when your work-in-progress is done and you want the PR merged.

**Comment by ksachdeva** [comment]
Hi Bjorn,

I believe the PR can be merged. I would add more definitions as I play with other APIs. 

Regards & thanks
Kapil

------------------------

**Comment by bihanssen** [comment]
The PR has now been merged. Thanks for the contribution.
BI

**Pull request closed without merging**
