### PR TITLE
Fix typings for createAdapter

### PR DESCRIPTION
**Pull request by ShaharHD**
Should be v2 and v5 (v3 is not an option anymore)

### CODE REVIEW

**Comment by ShaharHD** [comment]
@bencefr Hi, can you please look and approve this PR which fixes a typo which is blocks usage of the library with TypeScript

**Comment by bencefr** [comment]
Hi @ShaharHD , thank you for your contribution!

**Review by bencefr — APPROVED** [review]

**Comment by ShaharHD** [comment]
@bencefr when's the next npm release?

**Comment by ShaharHD** [comment]
@bencefr any updates on a version release which includes this?

**Pull request merged**
